"""initial

Revision ID: 4748c9f11967
Revises: 
Create Date: 2026-02-28 19:11:09.326849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4748c9f11967'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hospital_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('contact', sa.String(length=50), nullable=False),
    sa.Column('hospital_address', sa.String(length=500), nullable=False),
    sa.Column('icu_beds', sa.Integer(), nullable=False),
    sa.Column('hdu_beds', sa.Integer(), nullable=False),
    sa.Column('general_beds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('staff',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('specialty', sa.String(length=255), nullable=False),
    sa.Column('qualification', sa.String(length=255), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('contact', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('on_duty', sa.Boolean(), nullable=False),
    sa.Column('shift', sa.String(length=20), nullable=False),
    sa.Column('max_patients', sa.Integer(), nullable=False),
    sa.Column('current_patient_count', sa.Integer(), nullable=False),
    sa.Column('joined_date', sa.Date(), nullable=False),
    sa.Column('bio', sa.String(length=1000), nullable=True),
    sa.Column('languages', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('consultation_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_id')
    )
    op.create_table('admissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('patient_name', sa.String(length=255), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('emergency_contact', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('gov_id_type', sa.String(length=50), nullable=True),
    sa.Column('id_picture_url', sa.String(length=500), nullable=True),
    sa.Column('patient_picture_url', sa.String(length=500), nullable=True),
    sa.Column('guardian_name', sa.String(length=255), nullable=True),
    sa.Column('guardian_relation', sa.String(length=100), nullable=True),
    sa.Column('guardian_phone', sa.String(length=50), nullable=True),
    sa.Column('guardian_email', sa.String(length=255), nullable=True),
    sa.Column('whatsapp_number', sa.String(length=50), nullable=True),
    sa.Column('bed_id', sa.String(length=20), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('doctor_name', sa.String(length=255), nullable=False),
    sa.Column('admission_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('heart_rate', sa.Float(), nullable=True),
    sa.Column('spo2', sa.Float(), nullable=True),
    sa.Column('resp_rate', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('bp_systolic', sa.Float(), nullable=True),
    sa.Column('bp_diastolic', sa.Float(), nullable=True),
    sa.Column('measured_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('presenting_ailment', sa.Text(), nullable=True),
    sa.Column('medical_history', sa.Text(), nullable=True),
    sa.Column('clinical_notes', sa.Text(), nullable=True),
    sa.Column('lab_results', sa.Text(), nullable=True),
    sa.Column('severity_score', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('discharge_notes', sa.Text(), nullable=True),
    sa.Column('discharged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['staff.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('beds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('bed_id', sa.String(length=20), nullable=False),
    sa.Column('bed_type', sa.String(length=10), nullable=False),
    sa.Column('bed_number', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('current_patient_id', sa.Integer(), nullable=True),
    sa.Column('last_occupied_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['current_patient_id'], ['admissions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bed_id')
    )
    op.create_table('clinical_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admission_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('patient_name', sa.String(length=255), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_id'], ['staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_slots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.String(length=20), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('patient_name', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['staff.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['admissions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_slots')
    op.drop_table('clinical_notes')
    op.drop_table('beds')
    op.drop_table('admissions')
    op.drop_table('staff')
    op.drop_table('hospitals')
    # ### end Alembic commands ###
